"""Shared contracts owned by member A.

B, C and D import from here; only A changes these modules.

Layout:
    common.py    response envelope, error codes, cross-cutting enums,
                 currency placeholder (settlement currency only, FX reserved)
    product.py   Product and HardConstraints (the type D returns)
    search.py    A -> B search request/response       (pending: see docs)
    mandate.py   MandateDraft, Mandate, ApprovalGrant, canonical policy hashing
    commerce.py  Quote, PaymentRouteEvaluation, PurchaseProposal, Reservation, SpendState
    policy.py    PolicyDecision, PolicyViolation, DenialReceipt, EscalationRequest,
                 PaymentReceipt, PaymentFailure, ProposalOutcome
    agent.py     Intent vocabulary, IntentResult, parser and LLM boundaries
    audit.py     append-only hash-chained audit events
"""

from .agent import (
    MANDATE_INTENTS,
    SEARCH_INTENTS,
    AgentActionRequest,
    Ambiguity,
    AmbiguityKind,
    ChatRequest,
    Clarification,
    ConstraintPatch,
    Intent,
    IntentParser,
    IntentResult,
    LLMClient,
    LLMRequest,
    LLMResponse,
    ParseSource,
    ParserAttempt,
    SessionContext,
    TargetReference,
    UserActionType,
)
from .audit import (
    GENESIS_PREVIOUS_HASH,
    AuditEvent,
    AuditEventType,
    ChainBreak,
    VerifyReport,
    compute_event_hash,
    verify_chain,
)
from .commerce import (
    HOLDING_STATUSES,
    PaymentRouteEvaluation,
    PurchaseProposal,
    Quote,
    Reservation,
    ReservationStatus,
    SpendState,
)
from .common import (
    BUSINESS_OUTCOMES,
    DEFAULT_HTTP_STATUS,
    POLICY_DENIAL_CODES,
    SETTLEMENT_CURRENCY,
    SUPPORTED_CURRENCIES,
    ActorType,
    AgentPhase,
    Envelope,
    ErrorCode,
    ErrorDetail,
    Money,
    NextAction,
    PaymentRail,
    SourceType,
    http_status_for,
    is_business_outcome,
    is_retryable,
    new_request_id,
)
from .mandate import (
    ApprovalGrant,
    Mandate,
    MandateDraft,
    MandateStatus,
    canonical_bytes,
    policy_hash,
)
from .policy import (
    DenialReceipt,
    EscalationRequest,
    Outcome,
    PaymentFailure,
    PaymentReceipt,
    PolicyDecision,
    PolicyViolation,
    ProposalOutcome,
)
from .product import DEVICES, Device, HardConstraints, Product
from .profile import (
    FactSource,
    ProfileFact,
    ProfileGap,
    UserProfile,
    derive_soft_preferences,
    preference_profile_from,
)
from .search import (
    CONSTRAINT_TO_ATTRIBUTE,
    NATURAL_DIRECTION,
    NUMERIC_ATTRIBUTES,
    RELAXABLE_FIELDS,
    Candidate,
    ComparisonCell,
    ComparisonFrame,
    ComparisonRow,
    Criterion,
    DimensionStats,
    GapReport,
    MatchReason,
    OverBudgetAlternative,
    PreferenceProfile,
    RelaxHints,
    RelaxationOption,
    SearchOutcome,
    SearchRequest,
    SearchResponse,
    SearchResult,
    SummaryResponse,
    classify_outcome,
)

__all__ = [
    "BUSINESS_OUTCOMES",
    "CONSTRAINT_TO_ATTRIBUTE",
    "DEFAULT_HTTP_STATUS",
    "DEVICES",
    "NATURAL_DIRECTION",
    "NUMERIC_ATTRIBUTES",
    "POLICY_DENIAL_CODES",
    "RELAXABLE_FIELDS",
    "ActorType",
    "AgentActionRequest",
    "AgentPhase",
    "Ambiguity",
    "AmbiguityKind",
    "ApprovalGrant",
    "AuditEvent",
    "AuditEventType",
    "Candidate",
    "ChainBreak",
    "ChatRequest",
    "Clarification",
    "ComparisonCell",
    "ComparisonFrame",
    "ComparisonRow",
    "ConstraintPatch",
    "Criterion",
    "DenialReceipt",
    "Device",
    "DimensionStats",
    "Envelope",
    "ErrorCode",
    "ErrorDetail",
    "EscalationRequest",
    "GENESIS_PREVIOUS_HASH",
    "GapReport",
    "HOLDING_STATUSES",
    "HardConstraints",
    "Intent",
    "IntentParser",
    "IntentResult",
    "LLMClient",
    "LLMRequest",
    "LLMResponse",
    "MANDATE_INTENTS",
    "Mandate",
    "MandateDraft",
    "MandateStatus",
    "MatchReason",
    "Money",
    "NextAction",
    "Outcome",
    "OverBudgetAlternative",
    "ParseSource",
    "ParserAttempt",
    "PaymentRail",
    "PaymentFailure",
    "PaymentReceipt",
    "PaymentRouteEvaluation",
    "PolicyDecision",
    "PolicyViolation",
    "PreferenceProfile",
    "Product",
    "ProfileFact",
    "ProfileGap",
    "ProposalOutcome",
    "PurchaseProposal",
    "Quote",
    "RelaxHints",
    "RelaxationOption",
    "Reservation",
    "ReservationStatus",
    "SEARCH_INTENTS",
    "SETTLEMENT_CURRENCY",
    "SUPPORTED_CURRENCIES",
    "SearchOutcome",
    "SearchRequest",
    "SearchResponse",
    "SearchResult",
    "SessionContext",
    "SourceType",
    "FactSource",
    "SpendState",
    "SummaryResponse",
    "TargetReference",
    "UserActionType",
    "UserProfile",
    "VerifyReport",
    "canonical_bytes",
    "classify_outcome",
    "compute_event_hash",
    "http_status_for",
    "is_business_outcome",
    "is_retryable",
    "new_request_id",
    "policy_hash",
    "verify_chain",
]
